### ISSUE TITLE
metadata source facet - remove "Symphony" value?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#1007]
Question for Andrew - should we remove "Symphony" values from the metadata source facet in Argo?

![image](https://github.com/sul-dlss/dor_indexing_app/assets/96775/ede4f801-c443-410f-999b-35b42f5ca125)

We could NOT index "Symphony" if that was desired.  We can certainly keep it as long as it is desired.

https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/identifiable_indexer.rb#L30

**Comment by andrewjbtw** [comment]
I vote to keep it until we decide what to do with the "catkey" value.

**Comment by andrewjbtw** [comment]
Based on subsequent discussions, I think we can drop this from the facet even while we keep "catkey" in Cocina. I'll ticket that.
