### ISSUE TITLE
isolate workflow service deployment

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#106]
We'd like to have 2 sets of VMs -- one for the workflow service (java war, archiver, and oracle client) and another for the robot-master and resque queues (e.g., redis).
 
- [ ] create new VMs
  - [ ] use Java 6 for tomcat
- [ ] migrate workflow service and workflow-archiver-job
  - [x] update repos so that they are deployable
  - [ ] deploy workflow service and workflow-archiver-job to new VMs (workflow-*)
  - [ ] ensure we can connect to Oracle database from new VMs
  - [ ] deploy of .war file is via Jenkins currently
  - [ ] deploy workflow archiver (note it's linked to dor-services-app)
  - [ ] change all configurations for robots, Argo, dor-services-app, dor-indexing-app, and others(?) to point to the new workflow service (we will have httpd redirection so this isn't in the critical path)
- [ ] migrate robot-master
  - [ ] deploy robot-master to new VMs (sul-robots-redis*)
  - [ ] migrate redis database to new VMs (and point all robot VMs to it)
  - [ ] change all configurations for robots, Argo, dor-services-app, dor-indexing-app, and others(?) to point to the new redis
- [ ] purge lyberservices deploys
  - [ ] purge workflow service from tomcat
  - [ ] purge workflow service archiver, robot-master, and redis

**Comment by drh-stanford** [comment]
See SARs 3308 and 3309

**Comment by cbeer** [comment]
Related to https://github.com/sul-dlss/devops-concerns/issues/79
