### ISSUE TITLE
[dor_indexing_app/production] LoadError: cannot load such file -- active_fedora/associations/belongs_to_association

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#181]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/controllers/dor_controller.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/36636695)

**Comment by cbeer** [comment]
Same cause as #180.
