### ISSUE TITLE
[dor_indexing_app/production] RuntimeError: Solr document (id: druid:fy905cp2752) is missing required has_model_ssim field.

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#237]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/controllers/dor_controller.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/42856727)

**Comment by jcoyne** [comment]
Duplicate of #244
