### ISSUE TITLE
[dor_indexing_app/prod] RuntimeError: Solr document (id: druid:fy905cp2752) is missing required has_model_ssim field.

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#244]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/controllers/dor_controller.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/43144328)

**Comment by jcoyne** [comment]
I resolved this by going to dor_indexing_app and running:
```
ActiveFedora::SolrService.query('id:"druid:fy905cp2752"').first['has_model_ssim']
 => nil
Dor.find('druid:fy905cp2752').update_index
 => {"responseHeader"=>{"status"=>0, "QTime"=>47}}
ActiveFedora::SolrService.query('id:"druid:fy905cp2752"').first['has_model_ssim']
 => ["info:fedora/afmodel:Dor_Collection"]
```

still unsure about how it got to this state.
