### ISSUE TITLE
what should we be monitoring?

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#44]
- what should we be monitoring
- migrate to okcomputer
- including which systems, activemq, fedora, dor-indexing-app, etc.
- ...more

**Comment by jmartin-sul** [comment]
we definitely want to monitor fedora and solr, since without working connections to both of those dor_indexing_app is useless.

but it was also designed to be really simple (e.g. it uses no DB, doesn't deal with sessions, etc).  so i'm not sure there are any other systems it really depends on?

**Comment by drh-stanford** [comment]
we're going to have a discussion about this topic at 11am.

just some notes from discussion yesterday...we've been having an ongoing discussion about how to implement actionable monitoring alerts. it does seem that dor_indexing_app's internals are simple and there isn't really any internal subsystems to monitor.

fedora and solr are external systems on which dor_indexing_app depends so we want to account for connectivity in our monitoring somehow. with OkComputer we've been doing this with `/status/external-abc` routes.

an additional monitoring consideration for dor_indexing_app is the notion of "flow" -- that is, are objects actively flowing through the indexer, or is there no work going through. and if there is flow, what's the throughput like. that may be an ActiveMQ monitoring responsibility that the ReindexQueue is moving.

so the strawman right now would be:

- `/status/default` - a trivial ping (action: restart passenger)
- `/status/flow` - are objects being actively reindexed? (action: debug queuing?)
- `/status/external-fedora` - is the connection to Fedora working? (action: panic?)
- `/status/external-solr` - is the connection to Solr working? (action: panic?)

**Comment by eefahy** [comment]
Per our monitoring conversation: we would like a way to report performance information on the throughput of the stack. A potential way to do that is to include some benchmark data in logs and a nagios check on the content of those logs?

**Comment by drh-stanford** [comment]
also see https://github.com/sul-dlss/devops-concerns/issues/133, https://github.com/sul-dlss/devops-concerns/issues/132, https://github.com/sul-dlss/devops-concerns/issues/130, and https://github.com/sul-dlss/devops-concerns/issues/129

**Comment by drh-stanford** [comment]
whiteboard from 11/3 11am meeting:

![whiteboard_20161103](https://cloud.githubusercontent.com/assets/1861171/19982058/b9f0957e-a1c1-11e6-9b07-9b25ee3d0c6e.jpg)

**Comment by drh-stanford** [comment]
@eefahy note that Argo's monitoring is checking both the argo Solr core and Fedora connectivity. See https://github.com/sul-dlss/argo/blob/master/config/initializers/is_it_working.rb#L6

**Comment by drh-stanford** [comment]
we added `/status/external-queue-size` as a monitoring endpoint.
