### ISSUE TITLE
tune MQ concurrency configuration with dor_indexing_app threads

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#50]
see #44. we need to ensure that the max concurrent workers for MQ matches the max concurrent requests for the dor_indexing_app Rails instance.

for the consumer's concurrency see https://github.com/sul-dlss/dor-camel-routes/blob/master/deploy/edu_stanford_dor-indexing-app-prod.indexing.xml#L56

**Comment by drh-stanford** [comment]
Currently, MQ has a max of 30 concurrent requests and dor_indexing_app in prod has 20 per server. So I think we're fine here.

```
  PassengerMaxPoolSize 20
```

**Comment by drh-stanford** [comment]
I'm going to reopen this ticket because this is likely to be on-going tuning, and affected by #108.

**Comment by cbeer** [comment]
I'm going to follow up with @eefahy. I've tried tweaking numbers in various directions without much result. It's not clear to me where the bottleneck currently is for indexing throughput.
