### ISSUE TITLE
Decouple EmbargoMetadataDatastreamIndexer from ActiveFedora

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor_indexing_app#508]
We must resolve https://github.com/sul-dlss/dor-services-app/issues/2414 first

**Comment by ndushay** [comment]
Solr field `embargo_release_dtsim` is searched when Argo facet selector "Embargo Release Date" is used:

![image](https://user-images.githubusercontent.com/96775/112248060-8abeeb80-8c12-11eb-846b-b87d14cbe333.png)

**Comment by ndushay** [comment]
a key thing is that the embargo shows up in the purl correctly

**Comment by jcoyne** [comment]
Purl has no dependency on the dor_indexing_app or on the argo Solr index

**Comment by ndushay** [comment]
It probably makes sense to get https://github.com/sul-dlss/dor-services-app/issues/2682 addressed before doing this, so we have a way to test the soup to nuts for cocina embargo information.
