### ISSUE TITLE
Decouple IdentityMetadataDatastreamIndexer from ActiveFedora

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor_indexing_app#509]
and rename the class as "Datastream" will have no meaning in our brave new world. --

**Comment by ndushay** [comment]
Is this done?  If so, I'll do the renaming as part of a PR I'm doing now.

**Comment by ndushay** [comment]
(also, if this is done ... can it be closed?)

**Comment by ndushay** [comment]
rename in PR #544
