### ISSUE TITLE
Decouple RightsMetadataDatastreamIndexer from ActiveFedora

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor_indexing_app#510]
Depends on https://github.com/sul-dlss/argo/issues/2448

We must provide what DRA is doing now so we can have this facet:
<img width="394" alt="Screen Shot 2021-03-12 at 5 12 29 PM" src="https://user-images.githubusercontent.com/92044/111008234-3dab6180-8356-11eb-85c6-5e97dae92921.png">

Ensure we can do this item: https://argo-stage.stanford.edu/view/druid:nn734fw1198
<img width="450" alt="Screen Shot 2021-03-19 at 3 48 40 PM" src="https://user-images.githubusercontent.com/92044/111840715-ddbf3880-88ca-11eb-96ad-18ada94fade5.png">

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <group>stanford</group>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world rule="no-download"/>
    </machine>
  </access>
  <access type="read">
    <file>nn734fw1198_md.pdf</file>
    <machine>
      <world/>
    </machine>
  </access>
  </rightsMetadata>
 ```

**Comment by ndushay** [comment]
@jcoyne this requires more nuance in the cocina-model for access than is currently available ... who would be helping with that modeling work?

**Comment by ndushay** [comment]
PR #2402 is supposed to be addressing the file level access needs called out in #2302 ...

I think we would be well served to come up with a way to test: "does THIS rightsMetadata.xml end up getting mapped to cocina and indexed from cocina with the same solr values it got when it was being indexed from rightsMetadata.xml"

for all the wrinkles in the above comment and any other that mapping surfaces.

**Comment by ndushay** [comment]
NOTE:  PR for this should not be merged to main before  Wednesday morning, 4/28/21
