### ISSUE TITLE
[dor_indexing_app/stage] NoMethodError: undefined method `code' for nil:NilClass

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#527]
## Backtrace

    line 71 of [PROJECT_ROOT]/app/indexers/describable_indexer.rb: block in language
    line 70 of [PROJECT_ROOT]/app/indexers/describable_indexer.rb: map
    line 70 of [PROJECT_ROOT]/app/indexers/describable_indexer.rb: language

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/77790493)

**Comment by jcoyne** [comment]
The language here is:
```
    "language": [
      {
        "code": "eng",
        "value": "English"
      }
    ],
 ```
 
 See https://argo-stage.stanford.edu/view/bj286jw8159
