### ISSUE TITLE
No specs for some indexing class files

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#543]
- descriptive_metadata_indexer
- fedora3_label_indexer  <-- perhaps don't care as we hope to move on
- process_indexer

Obviously, it's not that the specs need to correspond exactly to the class files ... but I don't believe this code is tested anywhere.

**Comment by jcoyne** [comment]
@ndushay some of the tests test more than one class. so it's pretty well covered:

<img width="334" alt="Screen Shot 2021-03-24 at 11 25 06 AM" src="https://user-images.githubusercontent.com/92044/112346125-a6b6a180-8c93-11eb-90e9-e43d7b9cd7e5.png">

**Comment by ndushay** [comment]
ah thanks - I should have thought of checking coverage.  The rights_metadata_indexer will be improving with my nascent work, waiting on Mike's dor-services-app PR.

Closing this ticket.
