### ISSUE TITLE
[production] NoMethodError on rights to_solr call

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#55]
## Backtrace

    line 3 of [PROJECT_ROOT]/app/controllers/dor_controller.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/31542142)

```
NoMethodError: undefined method `value' for #<Nokogiri::XML::Element:0x000000033ad650>
```

**Comment by drh-stanford** [comment]
parameters:

```
{
  "commitWithin" => "10000",
  "controller" => "dor",
  "action" => "reindex",
  "pid" => "druid:bd909yc5623"
}
```

failure at rights_auth.rb  257  extract_index_terms(...)
[GEM_ROOT]/gems/dor-rights-auth-1.2.0/lib/dor/rights_auth.rb:257:in `extract_index_terms'

**Comment by jmartin-sul** [comment]
bug in dor-rights-auth xpath expectations?  this is where things go wrong:
https://github.com/sul-dlss/dor-rights-auth/blob/v1.2.0/lib/dor/rights_auth.rb#L257

**Comment by drh-stanford** [comment]
Ok, I created a ticket in dor-rights-auth: https://github.com/sul-dlss/dor-rights-auth/issues/24

**Comment by drh-stanford** [comment]
This has happened 2,427 in production thus far.
