### ISSUE TITLE
fix title indexing (spec'ed but not done)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#563]
### Background

There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

### What Needs to be Done

This ticket is to make the `sw_display_title_tesim` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Per PR #517, `sw_display_title_tesim` Solr field was formerly populated by calling `sw_title_display` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L193).  Tracing through the logic, you see something like this:

`sw_title_display` gets a value from `sw_full_title` and then removes specific trailing punctuation
`sw_full_title` gets a value from non-sorting title chars, then title, then " : " then subTitle and then does stuff with partName and partNumber if present ... and then does some stuff with trailing punctuation.

- Work with Arcadia to find the corresponding information ^^ in cocina models.
    - ask her what to do if there are mulitple title values in Cocina
- Write tests that exercise different use cases
- ensure you account for the possibility of parallel data (e.g. multilingual) and structured data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/title_info_spec.rb.    That is, if the code only expects "title.value" it won't finded any structuredValues or parallelValues, and all that good stuff.

### User Impact
We are likely not populating the title field for some use cases (e.g. when the data is multi-lingual, or when it is structured) and we are likely giving Argo users a mistaken impression of how their data will appear in SearchWorks.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

**Comment by ndushay** [comment]
tagging @arcadiafalcone to get her input on where to find the right data in Cocina.

**Comment by ndushay** [comment]
PR #574 adds a bunch of xit specs from Arcadia that show how to get title info from all the various cocina cases;  it does not necessarily have "first look here, then there" baked in -- you may need more specs for that part.

**Comment by arcadiafalcone** [comment]
PR #574 is really two sets of specs - the first part is about selecting the preferred title and the second part is about constructing the title string once the preferred title is determined.

**Comment by ndushay** [comment]
Arcadia's part of this ticket is done, but not the developer part!
