### ISSUE TITLE
fix genre indexing

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#566]
### Background
There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

This ticket is to make the `sw_genre_ssim` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Per PR #517, `sw_genre_ssim` Solr field was formerly populated by calling `sw_genre` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L305).  

"term_value" is from the "om" gem approach to metadata mapping from a bazillion years ago with Hydra (yes, it was Hydra then).  It is defined in the mods gem:  https://github.com/sul-dlss/mods/blob/master/lib/mods/nom_terminology.rb#L72.  It then seems to normalize what it finds with particular capitalizations.

I'm not sure how well the genre terms from stanford-mods correspond to the terms we use in Cocina -- You can look at what is in the SearchWorks genre facet https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=At+the+Library (that should cover most all of them).  You can also look at the mappings from MODS to Cocina here to get a sense of what wrinkles might be present in the Cocina genre data:   https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/genre_spec.rb.  

- Work with Arcadia to find the corresponding information ^^ in cocina models.
    - ask her how closely the Cocina genre information maps to what was in MODS; ask her and Andrew if Cocina data is more or less ok as is;  ask them what capitalization is expected, if it's a controlled vocabulary, etc. 
- Write tests that exercise the different use cases
- ensure you account for the possibility of more complex data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/genre_spec.rb.  

### User Impact
We are likely giving Argo users a mistaken impression of how their genre data will appear in SearchWorks.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

**Comment by ndushay** [comment]
tagging @arcadiafalcone to get her input on where to find the right data in Cocina.

**Comment by justinlittman** [comment]
@ndushay Arcadia wrote specs for this. Is implementing the specs adequate to resolve this or is additional work necessary?
