### ISSUE TITLE
fix format indexing

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#567]
### Background
There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

### What Needs To Be Done

This ticket is to make the `sw_format_ssim` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Per PR #517, `sw_format_ssim` Solr field was formerly populated by calling `format_main` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/searchworks.rb#L244).  Tracing through the logic,  you see
- there is a strict controlled vocabulary used
- there can be multiple formats 

"term_value" is from the "om" gem approach to metadata mapping from a bazillion years ago with Hydra (yes, it was Hydra then). It is defined in the mods gem: https://github.com/sul-dlss/mods/blob/master/lib/mods/nom_terminology.rb) -- you can see the stanford_mods looks for "typeOfResource",  "genre" and for "originInfo/issuance" and for "originInfo/frequency" . It then seems to normalize what it finds with particular capitalizations.

- Work with Arcadia to find ALL the corresponding information ^^ in cocina models.
- Write tests that exercise the different use cases
- ensure you account for the possibility of more complex data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g. https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/genre_spec.rb, originInfo for frequency and issuance, and ask Arcadia where to find the equiv for typeOfResource.    That is, if the code only expects "language.value" it won't find any values inside a parallelValue (multi-lingual) or structural block, etc. and all that sort of stuff.

### User Impact
We are likely not populating the format facet field for some use cases, missing values for other use cases and we are likely giving Argo users a mistaken impression of how their data will appear in SearchWorks.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

**Comment by ndushay** [comment]
tagging @arcadiafalcone to get her input on where to find the right data in Cocina.

**Comment by ndushay** [comment]
To identify periodicals, per Arcadia:  

> typeOfResource is "text" and any of: issuance is "continuing", issuance is "serial", frequency has a value

**Comment by jmartin-sul** [comment]
meetings and PR review kept me from making much progress on this.  one thing i discovered that might help if someone else picks this up:  if i un-`xit` tests in `spec/indexers/descriptive_metadata/format_spec.rb` for `sw_format_ssim`, i see that `sw_format_ssim` always comes back as `"Book"`, at least for:

```
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:226 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when software, multimedia assigns format based on resource type
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:94 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when dataset assigns format based on genre
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:204 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when notated music assigns format based on resource type
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:138 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when cartographic assigns format based on resource type
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:182 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when moving image assigns format based on resource type
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:116 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when manuscript assigns format based on resource type
rspec ./spec/indexers/descriptive_metadata/format_spec.rb:160 # DescriptiveMetadataIndexer form/genre mappings from Cocina to Solr sw_format_ssim when mixed material assigns format based on resource type
```

if i throw a `byebug` in `DescriptiveMetadataIndexer#sw_format` and run `format_spec.rb:160`, i can see that `resource_type` is `[]`, and so even the basic format mapping is skipped for the simpler output of `sw_format_for_text`.  i sort of doubt that fixing that alone would get back to parity with the stanford-mods based implementation we cut away from, but it seems like it'd be closer than the way things currently function.

un-assigning myself and putting back in ready.
