### ISSUE TITLE
decommission "legacy" deployment

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#57]
There's a `legacy` deployment of dor_indexing_app that uses `dor-services` 4.x. We need to decommission it.

**Comment by cbeer** [comment]
SAR-3301

**Comment by cbeer** [comment]
Removed the branch of this project.

**Comment by cbeer** [comment]
We stopped indexing to it back in https://github.com/sul-dlss/dor-camel-routes/commit/c3a81204f906bb4e2487e2c544858209b6336bb1

**Comment by cbeer** [comment]
The solr collection that was supporting this was previously removed.
