### ISSUE TITLE
fix pub year indexing

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#571]
### Background
There is a desire to keep certain DOR/Argo Solr index fields as similar to SearchWorks indexing as possible.  This was previously handled by using the same code in the `stanford-mods` gem for both this app and for SearchWorks to get the values for Solr fields.

PR #517 decoupled dor indexing from Fedora (MODS), but was done without this realization, so the algorithms for retrieving values for Solr from our (Cocina) descriptive metadata were inadvertently over-simplified.  Also, the original tests for the dor_indexing_app were not at all thorough in exploring different data conditions and how they would be indexed.

### What Needs to be Done
This ticket is to make the `sw_pub_date_facet_ssi` field contain values as much like the ones we were getting from the stanford-mods method as is reasonable.

Be certain PR #553 is merged before embarking on this ticket - it addresses part of this.

Per PR #517, `sw_pub_date_facet_ssi` Solr field was formerly populated by calling `pub_year_display_str` in stanford-mods (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/origin_info.rb#L47).  Tracing through the logic, you see it calls the `single_pub_year` method (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/origin_info.rb#L188).  This does fun processing first on the MODS dateIssued elements looking for a pub date and calling year_display_str (https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/origin_info.rb#L82) if there is a dateIssued element, then, if there isn't one, does similar logic on dateCreated MODS elements, and then looks at dateCaptured MODS elements.  PR #553 more or less deals with what would have been the dateIssued elements, but not the other flavors of dates.   Even for finding only what were the dateIssued elements in the MODS, there is a 3-tiered logic to identify these values in Cocina.  

- Work with Arcadia to find the corresponding information ^^ in cocina models.
    - ask her if there are nuances to the data
- Write tests that exercise the different use cases
- ensure you account for the possibility of more complex data in the relevant cocina models by referring to the appropriate mapping specs in the dor-services-app, e.g.https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/cocina/mapping/descriptive/mods/origin_info_date_spec.rb.  That is, if the code only expects "date.value" it won't find any values inside a structuredValue, a parallelValue (i.e. multi-lingual), and all that sort of stuff.

### User Impact

We are likely not populating the pub date field for some use cases and we are likely giving Argo users a mistaken impression of how their data will appear in SearchWorks.  This field is use in object titles in Argo, in a facet and probably in other places.

Note that in a perfect world, we will want to reindex all data that was indexed after PR #517 was deployed.

**Comment by ndushay** [comment]
tagging @arcadiafalcone to get her input on where to find the right data in Cocina.

**Comment by ndushay** [comment]
@arcadiafalcone this is partially implemented in PR #575 ... to the best of my ability, anyway.

**Comment by arcadiafalcone** [comment]
Single value, dateIssued > dateCreated > dateCaptured

1. event.type publication, date.type publication, date.status primary
2. event.type not publication, date.type publication, date.status primary
3. event.type publication, date.type nil, date.status primary
4. event.type publication, date.type publication, date.status not primary
5. event.type not publication, date.type publication, date.status not primary
6. event.type publication, date.type nil, date.status not primary
7. event.type creation, date.type creation, date.status primary
8. event.type not creation, date.type creation, date.status primary
9. event.type creation, date.type nil, date.status primary
10. event.type creation, date.type creation, date.status not primary
11. event.type not creation, date.type creation, date.status not primary
12. event.type creation, date.type nil, date.status not primary
13. event.type capture, date.type capture, date.status primary
14. event.type not capture, date.type capture, date.status primary
15. event.type capture, date.type nil, date.status primary
16. event.type capture, date.type capture, date.status not primary
17. event.type not capture, date.type capture, date.status not primary
18. event.type capture, date.type nil, date.status not primary

i. date.structuredValue, date.structuredValue.status primary
ii. date.structuredValue, date.structuredValue.type start
iii. date.structuredValue, date.structuredValue.type end (open-ended range)

a. date.parallelValue, date.parallelValue.status.primary
b. date.parallelValue.first

**Comment by ndushay** [comment]
PR #607 added specs from Arcadia.  To finish this ticket:

1. get all specs from Arcadia working.   spec/indexers/descriptive_metadata/pub_year_spec_1e.rb 
    - if they break existing specs, try to understand if the existing specs are wrong and/or talk to Arcadia about what to do
2. de-dup specs
- determine if each existing spec  spec/indexers/descriptive_metadata/pub_year_spec.rb  is a duplicate of one of Arcadia's. If so, remove it.  If not sure, keep it.
3.  combine pub_year_spec_1e.rb   and   pub_year_spec.rb   into a single file pub_year_spec.rb ... unless it makes sense to keep them separate for some reason.
