### ISSUE TITLE
should prod log_level be debug?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor_indexing_app#6]
is that the standard?  seems like a reasonable setting to launch with (and even keep if its not too noisy).  but i was mildly surprised it wasn't :info in the production settings.

**Comment by drh-stanford** [comment]
Yes, it's still set to `:debug` -- https://github.com/sul-dlss/dor_indexing_app/blob/master/config/environments/production.rb#L37

It looks like right now this is resulting in 1 type of event to be logged into `production.log`:

```
D, [2016-11-03T10:33:29.360632 #24715] DEBUG -- : source=rack-timeout id=a2b414f43216a63b6555095a30aa56d1 timeout=60000ms service=1ms state=active
```

So, I think we can safely set it to `:info`.

**Comment by cbeer** [comment]
:+1:. I think `:debug` is merely the Rails default.
