### ISSUE TITLE
Investigate the `delete_from_index` route

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#61]
The `/dor/delete_from_index/:pid` route is being used by an ActiveMQ consumer, but that route currently does not exist in the dor_indexing_app codebase.

See https://github.com/sul-dlss/dor-camel-routes/blob/master/deploy/edu_stanford_dor-indexing-app-prod.indexing.xml#L49

**Comment by cbeer** [comment]
That route was present in the Argo implementation:

https://github.com/sul-dlss/argo/blob/master/app/controllers/dor_controller.rb#L47

**Comment by drh-stanford** [comment]
So it looks like the deleted objects are sent to the `fedora.apim.update` topic, and then we parse it out to determine whether it's a delete action. I'll update the wiki docs -- see https://github.com/sul-dlss/dor-camel-routes/blob/master/deploy/apim_routing.xml#L75-L82
