### ISSUE TITLE
rights indexing from cocina is not yet correct

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#634]
dor-indexing-app

**Comment by ndushay** [comment]
JCoyne and JLitt know the most about the new rights indexing from cocina.

Andrew needs to sign off and what is in main is not okay (yet).

**Comment by ndushay** [comment]
@andrewjbtw - can you comment here or talk to Justin?

**Comment by andrewjbtw** [comment]
For object-level citation only, it should not report the files as  `dark (file)`.

For object-level rights where no file has exceptional rights, it should not report `(file)`. 

This collection of examples in stage covers all of the rights settings. There's a lot of objects with only object-level rights that are being reported as having `(file)` as well.
https://argo-stage.stanford.edu/catalog?f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=rights+examples

**Comment by andrewjbtw** [comment]
The object level rights are now being reported correctly on stage. But there are still two issues:

- when the object rights are citation, no file rights are being indexed
 - this should be `citation, stanford (no-download) (file)` https://argo-stage.stanford.edu/view/druid:nj198yr1733

- when there are two object-level read blocks for access, both values should be shown
 - this should be `stanford, location: ars` https://argo-stage.stanford.edu/view/druid:ff196pz3099

This object has all three options: two object read blocks and one file-level setting https://argo-stage.stanford.edu/view/druid:nn734fw1198
 It should be indexed as `stanford, world (no-download), and world (file)`
