### ISSUE TITLE
Unable to find "N-US" in authority "marcgac"

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dor_indexing_app#647]
**Describe the bug**

https://app.honeybadger.io/projects/49898/faults/79191626

**Comment by jcoyne** [comment]
@aaron-collier I don't think this is a bug in our code. Isn't the problem that the data in the marc record is not valid?

**Comment by jcoyne** [comment]
If we do want to disregard capitalization, then we should do it in DSA: https://github.com/sul-dlss/dor-services-app/pull/2806/files#diff-591f97ae6e03f11ecb7c2b5cc2c4de487a38cfcce4f02a2ea9b0416cac09c593R280-R282

**Comment by ndushay** [comment]
Is this a question for @arcadiafalcone  ?

**Comment by jcoyne** [comment]
I think so.

**Comment by arcadiafalcone** [comment]
I think we remediated this in the MARC data. Closing.
