### ISSUE TITLE
Deprecate the GET route in favor of POST

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#65]
We typically use POST or PUT rather than GET methods when the route is changing some state.

The implementation depends on whether camel can do a POST call. See https://github.com/sul-dlss/dor_indexing_app/blob/master/config/routes.rb#L5-L6

**Comment by cbeer** [comment]
We'll need to disable authenticity tokens for the reindexing routes in this application and hydrus.

**Comment by cbeer** [comment]
I think we did that already (for this application) with the Rails 5 upgrade.

**Comment by cbeer** [comment]
And Hydrus is apparently too old to have CSRF support.
