### ISSUE TITLE
[dor_indexing_app/qa] Rubydora::RecordNotFound: DigitalObject.find called for an object that doesn't exist

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor_indexing_app#741]
## Backtrace

    line 24 of [PROJECT_ROOT]/app/indexers/fallback_indexer.rb: fetch_object
    line 20 of [PROJECT_ROOT]/app/indexers/fallback_indexer.rb: to_solr
    line 25 of [PROJECT_ROOT]/app/services/indexer.rb: block in reindex_pid

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49898/faults/83922204)

**Comment by justinlittman** [comment]
Action for this ticket: Include the druid in the HB alert to allow troubleshooting.
