### ISSUE TITLE
Finish decommissioning old messaging architecture

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dor_indexing_app#840]
After Fedora VMs are turned off for good, we can ditch the messaging approach we used to index content out of Fedora:

- [x] Update the dor_indexing_app README to remove references to ActiveMQ / dor-camel-routes / etc.
- [x] Update / remove [dor DevOpsDocs](https://github.com/sul-dlss/DevOpsDocs/tree/c0fb015a17f718b1046a7dc9699e9e7891f1f6da/projects/dor), [sulmq DevOpsDocs](https://github.com/sul-dlss/DevOpsDocs/tree/master/projects/sulmq),  [infra portfolio shutdown docs](https://github.com/sul-dlss/DevOpsDocs/blob/5cd80d9b965f92dfd26a6e05a15b5b3812559720/infrastructure-shutdown-restart-ordering.md#core-underlying-services--fedora-sulmq-solr), [workflow server docs](https://github.com/sul-dlss/DevOpsDocs/blob/28ebff8f041dc50f53d09451be9a688d245fa9ef/projects/workflow-server-rails/operations-concerns.md#L9)
- [x] Deprecate / archive https://github.com/sul-dlss/dor-camel-routes repo
- [x] [Decommission sulmq VMs](https://github.com/sul-dlss/operations-tasks/issues/3078)
- [x] Update [workflow-server README](https://github.com/sul-dlss/workflow-server-rails/blob/cf41c9e9255ef726ecabf384e01d297984e3268f/README.md#todo)
- [x] Clean up shared configs, e.g., [workflow-prod](https://github.com/sul-dlss/shared_configs/blob/workflow-server-rails-prod/config/settings/production.yml#L13-L18) (but this is prolly one of at least a few branches needing cleanup)
- [x] Reflect change in [SDR service topology](https://docs.google.com/drawings/d/1hOkd-EOfsav51ma45yXoU-mM713MUhfKzwPs4zF41kY/edit)

**Comment by jcoyne** [comment]
I'm not sure this ticket can be advanced until we complete exporting the data from Fedora and decommission it.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> I'm not sure this ticket can be advanced until we complete exporting the data from Fedora and decommission it.

Can you say more? Is it because Fedora is still connecting to sulmq, and we're not sure what effect taking that down will have on the running Fedora instance? Or something else?

**Comment by mjgiarlo** [comment]
@jcoyne since we're restarting Fedora every few minutes, we could also edit its config file to sever the connection to sulmq, and then after the next restart, we should be golden to proceed with this issue? 🤷🏻‍♂️ cc: @justinlittman so he is aware we're discussing this.

**Comment by mjgiarlo** [comment]
This is now done since the MQ VMs are no longer.
