### ISSUE TITLE
remove Hydrus Collection and Hydrus APO facets

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#841]
There may also be an Argo component.

@andrewjbtw if you think this is worth doing, please leave a comment with your approval.  If not, close the ticket.

**Comment by andrewjbtw** [comment]
It's something worth doing where I need to get some more stakeholder input from the small number of people who are responsible for collections that are still considered "Hydrus collections" in the Argo facet.

**Comment by ndushay** [comment]
@andrewjbtw did this happen?  I thought I saw some work go by in the H2 board about this ...

**Comment by jcoyne** [comment]
@ndushay the collection part is done: https://github.com/sul-dlss/dor_indexing_app/pull/889

**Comment by ndushay** [comment]
@andrewjbtw do we still need the Hydrus APO facet?

**Comment by andrewjbtw** [comment]
I no longer see it in Argo, but I don't remember if that's because we dropped it from indexing or if my APO remediation removed the values that were still generating it.

The shorter answer is no, we don't need it.

**Comment by ndushay** [comment]
I think this may be done now -- I see them not.

**Comment by andrewjbtw** [comment]
I think there are still Hydrus APOs, technically speaking, but no separate facet for them anymore. I need to check on this again because I'm pretty sure I ran into a potential problem where remediating Hydrus APOs could be entangled with the H2/Argo version sync problem.

**Comment by ndushay** [comment]
I've affirmed that the Hydrus *collection* fields in the index have no data and that they are referenced only in a comment in DSA, which I am about to fix.  https://github.com/sul-dlss/dor-services-app/blob/main/spec/services/publish/rights_metadata_spec.rb#L6

**Comment by ndushay** [comment]
hydrus_apo_title_ssim is NOT populated in Argo prod
hydrus_apo_title_tesim is NOT populated in Argo prod

nonhydrus_apo_title_ssim is populated in Argo prod
 nonhydrus_apo_title_tesim is NOT populated in Argo prod

**Comment by ndushay** [comment]
with the PRs, this can be closed -- all references to these fields are gone in our code bases.
