### ISSUE TITLE
Change rolling reindexer strategy

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/dor_indexing_app#843]
Currently the rolling reindexer depends exclusively on currently indexed objects to determine what to reindex. If the indexed objects gets out of sync with actual objects (i.e., the objects in DSA PG), then some actual objects may never be indexed and some non-existent objects will persist in the index.

The rolling reindex should be changed so that:
* On a rolling basis, indexed objects are checked to verify that they exist and if not are deleted from the index.
* On a rolling basis, actual objects (where the list of actual comes from DSA) are reindexed.

**Comment by jcoyne** [comment]
The challenge here is providing backpressure. How do we make sure the indexer doesn't get behind the rate at which DSA can feed it data. We would prefer that rolling indexing requests are dropped rather than continue to queue. The current strategy (pulling from DSA) ensures there is no queue.

**Comment by jcoyne** [comment]
We might want to consider a second process that just ensures that everything is in the index.  Then our current rolling indexer would be sufficient. The downside here is that we now have two processes to manage.

**Comment by justinlittman** [comment]
@aaron-collier Here is my suggestion for implementing this:
1. Create a rolling reindexer in DSA which:
  * Reindexes an item by publishing a message to RabbitMQ. A new notification type will need to be created. The notification should include the model.
  * DROs / Collections / APOs should be selected for reindexing based on the first letter of the druid, where a different first letter is selected each day. (If I counted correctly there are 20 possible first letters, thus each druid will be reindexed every 20 days.). To get the letter for a particular day, `DateTime.now.ld % 20` will give you a number for the day which can be mapped into the 20 possible first letters.
  * Reindexing requests should be spaced out so that other indexing requests don't get delayed by a long queue.
2. Create a rolling deleter in DIA which:
  * Determines some number of the least recently updated items (similar to existing rolling reindexer). Given the rolling reindexer above, this number can probably be fairly small since items that need to be deleted will be at the top of this list after 20 days.
  * Checks DSA if each item exists.
  * If an item does not exist, then delete from Solr. Otherwise, ignore.

Happy to discuss more and/or split the work.

**Comment by ndushay** [comment]
sul-dlss/dor-services-app#4076 will likely remove the need for this.

**Comment by mjgiarlo** [comment]
With only two items missed in the index, we do not currently believe we need to work on this. But we may eventually. Iceboxing.

**Comment by ndushay** [comment]
can this be closed now?

**Comment by ndushay** [comment]
I'm closing this;  we now have a nightly job that checks for objects in SDR that aren't in Solr.  https://github.com/sul-dlss/dor-services-app/blob/main/config/schedule.rb#L42
