### ISSUE TITLE
EPIC: Enable formatted text in Martin Wong exhibit

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#851]
- Want titles italicized in text
- Want control over line breaks
- Need a way for info from SDR to allow formatting in exhibit
- Has a deadline of August 31st, 2022

See:

- https://github.com/sul-dlss/mods_display/issues/78 (line breaks)
- https://github.com/sul-dlss/exhibits/issues/1981 (italics - probably the more complex one)

**Comment by jcoyne** [comment]
@mjgiarlo is this in the right repo?

**Comment by jcoyne** [comment]
@mjgiarlo May I suggest dor-service-app instead?  Dor-indexing-app is only for argo and it doesn't do any formatting, so it isn't really pertinent to this issue.

**Comment by mjgiarlo** [comment]
@jcoyne DSA isn't currently included as a repo on the next WC board. We have 13 repos already so I'm not sure we want to add another one at this point. Wanna look at the list and make a suggestion? https://app.zenhub.com/workspaces/web-archiving--sdr-maint-june-july-2022-627dbfe861cf2d2f30928d5d/board

**Comment by mjgiarlo** [comment]
We finished this in July, I think. Closing.
