### ISSUE TITLE
Populate new Solr fields for released to SearchWorks and released to Earthworks

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#856]
we need a plan to get all the records indexed (could be just waiting for rolling reindexer to run through all our data, but if it's tractible to do it faster, that's fine.)

For now, it will be adequate to get this data for the records currently showing in Argo -- there is a separate epic for ensuring all SDR data is indexed (#852).

**Comment by andrewjbtw** [comment]
If we're removing the original "released to" facet we need to populate the new ones first. Otherwise we'll go weeks without up-to-date data.

**Comment by jcoyne** [comment]
We can see that these items are being indexed:
https://sul-solr-prod-a.stanford.edu/solr/#/argo3_prod/query?q=released_to_searchworks_dttsi:*&q.op=OR&indent=true&fl=released_to_searchworks_dttsi%20id

**Comment by ndushay** [comment]
Created a separte ticket for "remove Released To" facet - #3729
