### ISSUE TITLE
Add Folio as metadata source

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#942]
![image](https://user-images.githubusercontent.com/96775/221629352-c83978af-06fb-4641-9c7a-8147f7ae302f.png)

We want to keep the DOR and Symphony options and we now want to add the Folio option.

***The action for this ticket***:
- when the cocina has "folio" identifier (not "previous folio"), the metadata source should include Folio.  Could be in addition to Symphony.
- please verify this with Arcadia, including the exact cocina to look for, and what to do when there are both (during our transition period, before Aug 2023)

Code likely implicated:

```ruby
# app/indexers/identifiable_indexer.rb
    if cocina.identification&.catalogLinks&.any? { |link| link.catalog == 'symphony' }
      'Symphony'
```

```ruby
# spec/indexers/identifiable_indexer_spec.rb
      expect(indexer.identity_metadata_source).to eq 'Symphony'
# ...
        expect(doc).to match a_hash_including('metadata_source_ssi' => 'Symphony')
```

**Comment by ndushay** [comment]
Note:  any changes will require us to reindex everything with a Metadata Source facet value of Symphony, sooner or later

**Comment by andrewjbtw** [comment]
There's one more option:

- until migration: keep Symphony and add Folio
- after migration: remove Symphony

**Comment by arcadiafalcone** [comment]
My experiences with remediation and analysis suggest that having both Symphony and FOLIO in the facet would be helpful.

**Comment by peetucket** [comment]
I believe the current metadata source is a single valued Solr field.  So if we want to store multiple metadata sources here I think we'd need to change this field name and update Argo and any other consumers .  See https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/identifiable_indexer.rb#L21

**Comment by mjgiarlo** [comment]
@peetucket 💬 
> I believe the current metadata source is a single valued Solr field. So if we want to store multiple metadata sources here I think we'd need to change this field name and update Argo and any other consumers . See [`main`/app/indexers/identifiable_indexer.rb#L21](https://github.com/sul-dlss/dor_indexing_app/blob/main/app/indexers/identifiable_indexer.rb?rgh-link-date=2023-03-07T18%3A39%3A18Z#L21)

AFAICT, there are *very* few references to this field across our stack. It's just Argo and DIA, I believe. Changing this key does imply bulk reindexing in each env, though. Maybe one way to do this work is:

1. Start indexing `metadata_source_ssim` in addition to `metadata_source_ssi` in DIA
2. Add knowledge of `metadata_source_ssim` to Argo behind a feature flag
3. Mass reindexing
4. Once every object in every env has been indexed to have the new field, change Argo so that it exclusively uses `metadata_source_ssim`
5. Stop indexing `metadata_source_ssi` in DIA

❓

**Comment by peetucket** [comment]
That sounds like a reasonable approach Mike.
