### ISSUE TITLE
Dor Indexing App cleanup after Folio cutover

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#981]
## After Confirmation that All is Working Appropriately with Folio
Talk to Andrew and Arcadia to determine when we can stop indexing symphony identifiers (catkeys) - tagged them in question in comment below.

Also:

- [x] remove code such as `if Settings.catalog_record_id == 'symphony'`  
    - [x] identifiable_indexer + its spec (stop indexing catkey?)
    - [x] identity_metadata_indexer + its spec (stop indexing catkey?)
    - [x] spec/indexers/descriptive_metadata/title_spec.rb
- [ ] also search to see if there are any other spots.  E.g., search on, case insensitive, e.g.:
    - [ ] `catalogRecordId`
    - [ ] `catalog_record_id`
    - [ ] `ckey`
    - [ ] `catkey`
    - [ ] `symphony`
    - [ ] `ils`
    - [ ] `folio`
    - [ ] ...

**Comment by ndushay** [comment]
See https://docs.google.com/spreadsheets/d/1wrC_RL3tlOFrNeEAL5TBN09eRTj464cKc3E8P-BhfaE/

**Comment by ndushay** [comment]
@andrewjbtw @arcadiafalcone do we still want to index catkey?  Will there still be users searching for catkey?

**Comment by mjgiarlo** [comment]
> @andrewjbtw @arcadiafalcone do we still want to index catkey? Will there still be users searching for catkey?

@andrewjbtw @arcadiafalcone do y'all have a sense of this?

**Comment by arcadiafalcone** [comment]
I don't think it's necessary to continue to support catkey searching.

**Comment by andrewjbtw** [comment]
I concur. I think people are adjusting to the new format.
