### ISSUE TITLE
Investigate adding the SW author facet to Argo, indexed with same code as SearchWorks Author facet

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#994]
There is a desire to (re-)add a SW Author facet to Argo.  It was removed because folks were confused by the contents.   

Currently the results of https://github.com/sul-dlss/dor_indexing_app/blob/main/app/services/author_builder.rb are very different from https://github.com/sul-dlss/stanford-mods/blob/master/lib/stanford-mods/concerns/name.rb#L11. Initially investigate the data differences (add a report to DSA to extract the data used for comparison)

Check with @andrewjbtw if this should be solely for person Authors, as SearchWorks as a second facet for Author (organization) ... which could get similar treatment, or could be ignored, or could be combined into a single facet in Argo.  (My assumption is that SDR won't have a lot of organization authors we care about but what do I know?)

Use the same approach taken in #992:  (partial exemplar PR #993)

- determine which Solr field is used for the author facet in SearchWorks (probably via catalog_config or some such blacklight thing)
- determine from searchworks_traject_indexer how that field is indexed (see https://docs.google.com/spreadsheets/d/1s4gQcPEY_YPGrDOFXQQ1IbRYBc3AaKGRIPW1FFw46G0 ).
- if the indexing logic is encapsulated in the stanford_mods gem, as for the other SW facet fields in Argo, then proceed as PR #993 indicates to add indexing code here.
- after indexing code is merged and deployed, prepare PR that configures Argo to include the new facet.  Talk to Andrew about timing - should it appear before it is fully populated, etc.

If the course ahead is less straightforward, discuss with Naomi / Andrew about whether it's worth it.

**Comment by ndushay** [comment]
Andrew is skeptical whether this is a useful facet.  Argo is not a research tool;  it's an SDR management tool.  So it is less important that folks can facet on author ... (unless there is demand for this, unknown to Andrew).

Also, in SearchWorks, there is MARC metadata which provides author information totally differently from MODS, and obviously the conversion to and from cocina <-- --> MODS makes it even more confusing.

Thus, we would need a strong motivating case for an author facet in Argo to make it worth the trouble.

**Comment by ndushay** [comment]
We could use PR #1013 to index to a new field, and then use the qt=qttest url param in Argo to see the contents of a facet using the approach from PR #1013.

**Comment by ndushay** [comment]
@aaron-collier @arcadiafalcone can either of you recall if there was a report done for authors?

**Comment by ndushay** [comment]
If there is no more information at this time, then we should close this ticket and the draft PR #1013.   We can open a new ticket if we decide to have an author facet.

**Comment by ndushay** [comment]
I'm closing this and the PR and removing the branch.   We do NOT want this any more, AFAIR.   I'm pretty sure Andrew and I had this conversation.

**Comment by andrewjbtw** [comment]
Agreed. The complexity of parsing the metadata in Argo was outweighing the expected benefits.
