### ISSUE TITLE
Argo blacklight configuration and Solr indexing - any simplifications from #998?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor_indexing_app#999]
#998 is about winnowing the below down to 2 values:

- No MODS typeOfResource
- No SW Resource Type

https://github.com/sul-dlss/argo/blob/72ee31b069007813b57ed42971a7349595188de9/app/controllers/catalog_controller.rb#L156-L177

![image](https://github.com/sul-dlss/dor_indexing_app/assets/96775/52fa5e72-a458-4669-b768-795173e63b42)

The work of this ticket is to determine if 
- any of the Blacklight configuration code that can disappear with this change
- are any Argo indexing choices that can change (e.g. do we need to make the copyright field searchable in Solr? Or just retrievable?).

For example, do we make use of "SolrDocument::FIELD_COPYRIGHT" or "SolrDocument::FIELD_USE_STATEMENT" elsewhere?  Do we need these declarations to do something with Blacklight, or were they created only for the Empty Fields facet?   I tried to chase the code paths but I got confused in the midst of Presenters and other forms of indirection.

The less noise/useless code/configurations we have in Argo and in our Solr indexing, the better.

**Comment by andrewjbtw** [comment]
It's possible that those fields are used in the Profile view: https://argo.stanford.edu/profile?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+H2

**Comment by ndushay** [comment]
@jmartin-sul - please focus only on the config stuff in catalog_controller, as I have been perusing the indexing code at this time.

**Comment by jmartin-sul** [comment]
> @jmartin-sul - please focus only on the config stuff in catalog_controller, as I have been perusing the indexing code at this time.

will do!

**Comment by ndushay** [comment]
I didn't find anything easy to remove, so closing this.
